### ISSUE TITLE
Empty Folder after download

### ISSUE THREAD

**Issue by jeffxsc** [TsainGra/DeepSpeech#1]
Hi, thanks for your great work!
I'm trying to run your work but got stuck at the first step. I changed urlib2 to urlib.request and ran the download.py but turned out that I got an empty folder.
Trying to solve this, I downloaded the data manually and unzipped them in the folder but I still got stuck in the "generate_txt_file.py" due to the NotADirectoryError.
Any idea to solve this? Thx!!!

**Comment by Arrowa70** [comment]
In the first file, he made a spelling mistake....speaker's name...

**Comment by TsainGra** [comment]
Yes. Changed that let me know if you are still facing an issue.
